apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
  {{- include "helm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.postgres.type }}
  selector:
    app: postgres
  {{- include "helm.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.postgres.ports | toYaml | nindent 2 -}}