apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  labels:
  {{- include "helm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.rabbitmq.type }}
  selector:
    app: rabbitmq
  {{- include "helm.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.rabbitmq.ports | toYaml | nindent 2 -}}