apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
  {{- include "helm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.redis.type }}
  selector:
    app: redis
  {{- include "helm.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.redis.ports | toYaml | nindent 2 -}}