apiVersion: v1
kind: Service
metadata:
  name: newslingo-frontend
  namespace: newslingo
spec:
  type: ClusterIP
  selector:
    app: newslingo-frontend
  ports:
    - port: 3000
      targetPort: 3000
