apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-worker-news
  namespace: newslingo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: celery-worker-news
  template:
    metadata:
      labels:
        app: celery-worker-news
    spec:
      containers:
      - name: celery-worker-news
        image: localhost:5000/celery_app:1.0
        command: ["celery", "-A", "celery_app.scheduler", "worker", "--loglevel=info"]
        env:
        - name: CELERY_BROKER_URL
          value: "rabbitmq"
        - name: REDIS_EXTERNAL_SERVER_HOST
          value: "redis"
