fullnameOverride: newslingo-frontend
newslingoFrontend:
  image:
    repository: localhost:5000/newslingo-frontend
    tag: latest
  ports:
  - port: 80
    targetPort: 80
  replicas: 1
  type: ClusterIP
